// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"time"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
)

// MetricSettings provides common settings for a particular metric.
type MetricSettings struct {
	Enabled bool `mapstructure:"enabled"`
}

// MetricsSettings provides settings for redfishreceiver metrics.
type MetricsSettings struct {
	HwFanSpeed          MetricSettings `mapstructure:"hw.fan.speed"`
	HwNetworkIoReceive  MetricSettings `mapstructure:"hw.network.io.receive"`
	HwNetworkIoTransmit MetricSettings `mapstructure:"hw.network.io.transmit"`
	HwNetworkUp         MetricSettings `mapstructure:"hw.network.up"`
	HwTemperature       MetricSettings `mapstructure:"hw.temperature"`
}

func DefaultMetricsSettings() MetricsSettings {
	return MetricsSettings{
		HwFanSpeed: MetricSettings{
			Enabled: true,
		},
		HwNetworkIoReceive: MetricSettings{
			Enabled: true,
		},
		HwNetworkIoTransmit: MetricSettings{
			Enabled: true,
		},
		HwNetworkUp: MetricSettings{
			Enabled: true,
		},
		HwTemperature: MetricSettings{
			Enabled: true,
		},
	}
}

type metricHwFanSpeed struct {
	data     pmetric.Metric // data buffer for generated metric.
	settings MetricSettings // metric settings provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills hw.fan.speed metric with initial data.
func (m *metricHwFanSpeed) init() {
	m.data.SetName("hw.fan.speed")
	m.data.SetDescription("Fan speed in revolutions per minute")
	m.data.SetUnit("rpm")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricHwFanSpeed) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, idAttributeValue string, nameAttributeValue string, parentAttributeValue string) {
	if !m.settings.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutString("id", idAttributeValue)
	dp.Attributes().PutString("name", nameAttributeValue)
	dp.Attributes().PutString("parent", parentAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricHwFanSpeed) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricHwFanSpeed) emit(metrics pmetric.MetricSlice) {
	if m.settings.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricHwFanSpeed(settings MetricSettings) metricHwFanSpeed {
	m := metricHwFanSpeed{settings: settings}
	if settings.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricHwNetworkIoReceive struct {
	data     pmetric.Metric // data buffer for generated metric.
	settings MetricSettings // metric settings provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills hw.network.io.receive metric with initial data.
func (m *metricHwNetworkIoReceive) init() {
	m.data.SetName("hw.network.io.receive")
	m.data.SetDescription("Received network traffic in bytes")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.MetricAggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricHwNetworkIoReceive) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, idAttributeValue string, nameAttributeValue string, parentAttributeValue string) {
	if !m.settings.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutString("id", idAttributeValue)
	dp.Attributes().PutString("name", nameAttributeValue)
	dp.Attributes().PutString("parent", parentAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricHwNetworkIoReceive) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricHwNetworkIoReceive) emit(metrics pmetric.MetricSlice) {
	if m.settings.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricHwNetworkIoReceive(settings MetricSettings) metricHwNetworkIoReceive {
	m := metricHwNetworkIoReceive{settings: settings}
	if settings.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricHwNetworkIoTransmit struct {
	data     pmetric.Metric // data buffer for generated metric.
	settings MetricSettings // metric settings provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills hw.network.io.transmit metric with initial data.
func (m *metricHwNetworkIoTransmit) init() {
	m.data.SetName("hw.network.io.transmit")
	m.data.SetDescription("Transmitted network traffic in bytes")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.MetricAggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricHwNetworkIoTransmit) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, idAttributeValue string, nameAttributeValue string, parentAttributeValue string) {
	if !m.settings.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutString("id", idAttributeValue)
	dp.Attributes().PutString("name", nameAttributeValue)
	dp.Attributes().PutString("parent", parentAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricHwNetworkIoTransmit) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricHwNetworkIoTransmit) emit(metrics pmetric.MetricSlice) {
	if m.settings.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricHwNetworkIoTransmit(settings MetricSettings) metricHwNetworkIoTransmit {
	m := metricHwNetworkIoTransmit{settings: settings}
	if settings.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricHwNetworkUp struct {
	data     pmetric.Metric // data buffer for generated metric.
	settings MetricSettings // metric settings provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills hw.network.up metric with initial data.
func (m *metricHwNetworkUp) init() {
	m.data.SetName("hw.network.up")
	m.data.SetDescription("Link status 1 (up) or 0 (down)")
	m.data.SetUnit("")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricHwNetworkUp) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, idAttributeValue string, nameAttributeValue string, parentAttributeValue string) {
	if !m.settings.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutString("id", idAttributeValue)
	dp.Attributes().PutString("name", nameAttributeValue)
	dp.Attributes().PutString("parent", parentAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricHwNetworkUp) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricHwNetworkUp) emit(metrics pmetric.MetricSlice) {
	if m.settings.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricHwNetworkUp(settings MetricSettings) metricHwNetworkUp {
	m := metricHwNetworkUp{settings: settings}
	if settings.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricHwTemperature struct {
	data     pmetric.Metric // data buffer for generated metric.
	settings MetricSettings // metric settings provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills hw.temperature metric with initial data.
func (m *metricHwTemperature) init() {
	m.data.SetName("hw.temperature")
	m.data.SetDescription("Temperature in degrees Celsius")
	m.data.SetUnit("Cel")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricHwTemperature) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, idAttributeValue string, nameAttributeValue string, parentAttributeValue string) {
	if !m.settings.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutString("id", idAttributeValue)
	dp.Attributes().PutString("name", nameAttributeValue)
	dp.Attributes().PutString("parent", parentAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricHwTemperature) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricHwTemperature) emit(metrics pmetric.MetricSlice) {
	if m.settings.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricHwTemperature(settings MetricSettings) metricHwTemperature {
	m := metricHwTemperature{settings: settings}
	if settings.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user settings.
type MetricsBuilder struct {
	startTime                 pcommon.Timestamp   // start time that will be applied to all recorded data points.
	metricsCapacity           int                 // maximum observed number of metrics per resource.
	resourceCapacity          int                 // maximum observed number of resource attributes.
	metricsBuffer             pmetric.Metrics     // accumulates metrics data before emitting.
	buildInfo                 component.BuildInfo // contains version information
	metricHwFanSpeed          metricHwFanSpeed
	metricHwNetworkIoReceive  metricHwNetworkIoReceive
	metricHwNetworkIoTransmit metricHwNetworkIoTransmit
	metricHwNetworkUp         metricHwNetworkUp
	metricHwTemperature       metricHwTemperature
}

// metricBuilderOption applies changes to default metrics builder.
type metricBuilderOption func(*MetricsBuilder)

// WithStartTime sets startTime on the metrics builder.
func WithStartTime(startTime pcommon.Timestamp) metricBuilderOption {
	return func(mb *MetricsBuilder) {
		mb.startTime = startTime
	}
}

func NewMetricsBuilder(settings MetricsSettings, buildInfo component.BuildInfo, options ...metricBuilderOption) *MetricsBuilder {
	mb := &MetricsBuilder{
		startTime:                 pcommon.NewTimestampFromTime(time.Now()),
		metricsBuffer:             pmetric.NewMetrics(),
		buildInfo:                 buildInfo,
		metricHwFanSpeed:          newMetricHwFanSpeed(settings.HwFanSpeed),
		metricHwNetworkIoReceive:  newMetricHwNetworkIoReceive(settings.HwNetworkIoReceive),
		metricHwNetworkIoTransmit: newMetricHwNetworkIoTransmit(settings.HwNetworkIoTransmit),
		metricHwNetworkUp:         newMetricHwNetworkUp(settings.HwNetworkUp),
		metricHwTemperature:       newMetricHwTemperature(settings.HwTemperature),
	}
	for _, op := range options {
		op(mb)
	}
	return mb
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	if mb.metricsCapacity < rm.ScopeMetrics().At(0).Metrics().Len() {
		mb.metricsCapacity = rm.ScopeMetrics().At(0).Metrics().Len()
	}
	if mb.resourceCapacity < rm.Resource().Attributes().Len() {
		mb.resourceCapacity = rm.Resource().Attributes().Len()
	}
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption func(pmetric.ResourceMetrics)

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	return func(rm pmetric.ResourceMetrics) {
		var dps pmetric.NumberDataPointSlice
		metrics := rm.ScopeMetrics().At(0).Metrics()
		for i := 0; i < metrics.Len(); i++ {
			switch metrics.At(i).Type() {
			case pmetric.MetricTypeGauge:
				dps = metrics.At(i).Gauge().DataPoints()
			case pmetric.MetricTypeSum:
				dps = metrics.At(i).Sum().DataPoints()
			}
			for j := 0; j < dps.Len(); j++ {
				dps.At(j).SetStartTimestamp(start)
			}
		}
	}
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(rmo ...ResourceMetricsOption) {
	rm := pmetric.NewResourceMetrics()
	rm.Resource().Attributes().EnsureCapacity(mb.resourceCapacity)
	ils := rm.ScopeMetrics().AppendEmpty()
	ils.Scope().SetName("otelcol/redfishreceiver")
	ils.Scope().SetVersion(mb.buildInfo.Version)
	ils.Metrics().EnsureCapacity(mb.metricsCapacity)
	mb.metricHwFanSpeed.emit(ils.Metrics())
	mb.metricHwNetworkIoReceive.emit(ils.Metrics())
	mb.metricHwNetworkIoTransmit.emit(ils.Metrics())
	mb.metricHwNetworkUp.emit(ils.Metrics())
	mb.metricHwTemperature.emit(ils.Metrics())
	for _, op := range rmo {
		op(rm)
	}
	if ils.Metrics().Len() > 0 {
		mb.updateCapacity(rm)
		rm.MoveTo(mb.metricsBuffer.ResourceMetrics().AppendEmpty())
	}
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user settings, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(rmo ...ResourceMetricsOption) pmetric.Metrics {
	mb.EmitForResource(rmo...)
	metrics := pmetric.NewMetrics()
	mb.metricsBuffer.MoveTo(metrics)
	return metrics
}

// RecordHwFanSpeedDataPoint adds a data point to hw.fan.speed metric.
func (mb *MetricsBuilder) RecordHwFanSpeedDataPoint(ts pcommon.Timestamp, val int64, idAttributeValue string, nameAttributeValue string, parentAttributeValue string) {
	mb.metricHwFanSpeed.recordDataPoint(mb.startTime, ts, val, idAttributeValue, nameAttributeValue, parentAttributeValue)
}

// RecordHwNetworkIoReceiveDataPoint adds a data point to hw.network.io.receive metric.
func (mb *MetricsBuilder) RecordHwNetworkIoReceiveDataPoint(ts pcommon.Timestamp, val int64, idAttributeValue string, nameAttributeValue string, parentAttributeValue string) {
	mb.metricHwNetworkIoReceive.recordDataPoint(mb.startTime, ts, val, idAttributeValue, nameAttributeValue, parentAttributeValue)
}

// RecordHwNetworkIoTransmitDataPoint adds a data point to hw.network.io.transmit metric.
func (mb *MetricsBuilder) RecordHwNetworkIoTransmitDataPoint(ts pcommon.Timestamp, val int64, idAttributeValue string, nameAttributeValue string, parentAttributeValue string) {
	mb.metricHwNetworkIoTransmit.recordDataPoint(mb.startTime, ts, val, idAttributeValue, nameAttributeValue, parentAttributeValue)
}

// RecordHwNetworkUpDataPoint adds a data point to hw.network.up metric.
func (mb *MetricsBuilder) RecordHwNetworkUpDataPoint(ts pcommon.Timestamp, val int64, idAttributeValue string, nameAttributeValue string, parentAttributeValue string) {
	mb.metricHwNetworkUp.recordDataPoint(mb.startTime, ts, val, idAttributeValue, nameAttributeValue, parentAttributeValue)
}

// RecordHwTemperatureDataPoint adds a data point to hw.temperature metric.
func (mb *MetricsBuilder) RecordHwTemperatureDataPoint(ts pcommon.Timestamp, val float64, idAttributeValue string, nameAttributeValue string, parentAttributeValue string) {
	mb.metricHwTemperature.recordDataPoint(mb.startTime, ts, val, idAttributeValue, nameAttributeValue, parentAttributeValue)
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...metricBuilderOption) {
	mb.startTime = pcommon.NewTimestampFromTime(time.Now())
	for _, op := range options {
		op(mb)
	}
}
